apiVersion: apps/v1
kind: Deployment
metadata:
  name: banco-noticias-deployment
spec:
  template:
    metadata:
      name: banco-noticias
      labels:
        app: banco-noticias
    spec:
      containers:
        - name: banco-noticias-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: banco-configmap
  replicas: 1
  selector:
    matchLabels:
      app: banco-noticias