apiVersion: v1
kind: Pod
metadata:
  name: banco-noticias
  labels:
    app: banco-noticias
spec:
  containers:
    - name: banco-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: banco-configmap