apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      # targetPort: 80 -- Se o targetPort não for definido, entao e usado o port
      nodePort: 30000 # Pode ser um valor entre 30000 e 32767
  selector:
    app: portal-noticias
