apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001 # Pode ser um valor entre 30000 e 32767
  selector:
    app: sistema-noticias
